# Generated by Django 5.2.10 on 2026-04-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='record_id',
            field=models.CharField(blank=True, help_text='Primary key of the modified record in its original table', max_length=255, null=True),
        ),
    ]
