# Generated by Django 5.2.10 on 2026-04-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último cambio de contraseña'),
        ),
    ]
