# Generated by Django 5.2.10 on 2026-03-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS')], max_length=10)),
                ('content', models.TextField()),
                ('size_bytes', models.PositiveIntegerField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='projects.project')),
            ],
            options={
                'verbose_name': 'archivo subido',
                'verbose_name_plural': 'archivos subidos',
                'db_table': 'uploaded_files',
                'unique_together': {('project', 'filename')},
            },
        ),
    ]
