# Generated by Django 5.2.10 on 2026-03-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='content',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Fallas', 'Fallas')], max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_result', to='audit.uploadedfile')),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], max_length=20)),
                ('wcag_rule', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('line_number', models.PositiveIntegerField()),
                ('code_snippet', models.TextField()),
                ('affected_element', models.TextField()),
                ('audit_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.auditresult')),
            ],
            options={
                'verbose_name': 'hallazgo de accesibilidad',
                'verbose_name_plural': 'hallazgos de accesibilidad',
                'db_table': 'hallazgos_accesibilidad',
            },
        ),
    ]
