# Generated by Django 5.2.10 on 2026-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_uploadedfile_created_at_uploadedfile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='wcag_level',
            field=models.CharField(choices=[('A', 'A'), ('AA', 'AA'), ('AAA', 'AAA')], default='A', max_length=3),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('improvement', 'Improvement')], max_length=20),
        ),
    ]
