sonar.projectKey=opticode-frontend
sonar.projectName=Opticode Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.inclusions=**/*.js,**/*.jsx,**/*.css

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.vite/**,**/storybook-static/**,**/*.min.js,**/package-lock.json
