import io
from django.http import FileResponse
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from weasyprint import HTML

class AuditReportPDFView(APIView):
    """
    Endpoint: GET /api/audit/<fileId>/report/pdf/
    Generates a PDF report using WeasyPrint based on the file ID.
    """
    permission_classes = [IsAuthenticated]

    def get(self, request, fileId, *args, **kwargs):
        # We can construct HTML data here or load a template
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Audit Report - File {fileId}</title>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    padding: 40px;
                    color: #333;
                }}
                h1 {{
                    color: #1a4f76;
                    border-bottom: 2px solid #1a4f76;
                    padding-bottom: 10px;
                }}
                p {{
                    font-size: 14px;
                    line-height: 1.6;
                }}
                .header-info {{
                    margin-bottom: 30px;
                    background: #f8f9fa;
                    padding: 15px;
                    border-radius: 5px;
                }}
            </style>
        </head>
        <body>
            <h1>Audit Report</h1>
            <div class="header-info">
                <p><strong>File ID:</strong> {fileId}</p>
                <p><strong>Generated By:</strong> {request.user.email if hasattr(request.user, 'email') else 'Unknown'}</p>
            </div>
            <p>This is an automatically generated audit report covering the analysis findings for file <strong>{fileId}</strong>.</p>
        </body>
        </html>
        """

        # Convert HTML to PDF using WeasyPrint
        pdf_bytes = HTML(string=html_content).write_pdf()

        # Wrap in buffer and return as FileResponse
        buffer = io.BytesIO(pdf_bytes)
        buffer.seek(0)

        filename = f"audit_report_{fileId}.pdf"
        response = FileResponse(buffer, as_attachment=True, filename=filename)
        return response